#!/bin/sh

if [ -z $1 ]; then
    echo "Usage: store-case <directory>"
    exit 1
fi

if [ ! -d $1 ]; then
    echo "Creating directory $1"
    mkdir -p $1
fi

cp structure.dat rzpsi.dat carre.dat btor.dat $1
cp carre.out $1
[ -e virtualstructure.out ] && cp virtualstructure.out $1
[ -e carreFinal00000.silo ] && cp carreFinal00000.silo $1
[ -e traduit.out ] && cp traduit.out $1
[ -e traduitAAA00000 ] && cp traduitAAA00000 $1
[ -e traduit.out.b2 ] && cp traduit.out.b2 $1
[ -e traduit.out.sonnet ] && cp traduit.out.sonnet $1
cp vertex_data.out $1
cp selptx.inf $1
[ -e gmeta ] && cp gmeta $1
