#!/bin/sh

if [ -z $1 ]; then
    echo "Usage: store-case <directory>"
    exit 1
fi

cp structure.dat rzpsi.dat carre.dat btor.dat $1
cp virtualstructure.out $1
cp carreFinal00000.silo carre.out $1
cp traduitAAA00000 traduit.out $1
cp selptx.inf $1
