      subroutine pltini
c
c  version : 19.04.2000 22:29
c
      return
      end
      subroutine cadre
      return
      end
      subroutine motifs
      return
      end
      subroutine pltend
      return
      end
c=======================================================================
      subroutine cntour(f1,f2,n1,n2,xmin,xmax,ymin,ymax)
      return
      end
c=======================================================================
      subroutine trace(x1,x2,y1,y2,separx,separy,ptsep,npx,nptot,
     .        nstruc,npstru,xstruc,ystruc,nivx,nivy,
     .        nivtot,nbniv,np1,npr,xmail,ymail,nreg)
      return
      end
c=======================================================================
      subroutine trace2(x1,x2,y1,y2,separx,separy,ptsep,npx,nptot,
     .        nstruc,npstru,xstruc,ystruc,nivx,nivy,
     .        nivtot,nbniv,pntrat,dixtxo,xn,yn,nn1)
      return
      end
c=======================================================================
      subroutine trace3(x1,x2,y1,y2,separx,separy,ptsep,npx,nptot,
     .        nstruc,npstru,xstruc,ystruc,nivx,nivy,
     .        nivtot,nbniv,pntrat,dixtxo,xn,yn,nn1,
     .        repart,xptxo,yptxo,fctini,xfin,yfin,fctfin,
     .        a00,a01,a10,a11,psi,nx,ny,x,y)
      return
      end
